# permissions to do edit cronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-editor-role
rules:
- apiGroups:
  - batch.axsaucedo.io
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.axsaucedo.io
  resources:
  - cronjobs/status
  verbs:
  - get
  - patch
  - update
